version: '3.9'
services:
  mysql-db:
    image: mysql:latest
    tty: true
    restart: 'unless-stopped'
    container_name: mysql-db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      - MYSQL_DATABASE=db_production
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  api:
    build: .
    container_name: api
    tty: true
    restart: 'unless-stopped'
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - '3333:3333'
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      DATABASE_URL: "mysql://root:12345@mysql-db:3306/db_production"
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
